---
- name: Add repository key to the system
  apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8
  tags: 
    - mysql
    
- name: Install MariaDB repository
  apt_repository: repo='deb [arch=amd64,i386,ppc64el] http://mirrors.dotsrc.org/mariadb/repo/10.2/ubuntu xenial main' state=present
  tags: 
    - mysql

- name: Install Server
  apt: pkg=mariadb-server state=latest update_cache=yes
  tags:
    - mysql

- name: Install client
  apt: pkg=mariadb-client state=latest update_cache=yes
  tags:
    - mysql

- name: Install python-mysqldb
  apt: pkg=python-mysqldb state=latest update_cache=yes
  tags:
    - mysql

- name: Copy .my.cnf file with root password credentials - root
  template: src=root.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  when: MYSQL_ROOT_PASSWORD is defined
  tags:
    - mysql
