---
- name: Download composer installer file signature
  get_url:
    url: https://composer.github.io/installer.sig
    dest: /tmp/composer-installer.sig
    mode: 0644
    force: true
  # Download to localhost in order to use "lookup('file', …)" later
  # (cf. https://docs.ansible.com/ansible/2.5/plugins/lookup.html#lookup-plugins).
  delegate_to: localhost
  become: false
  tags: composer

- name: Set facts
  set_fact:
    composer_installer_sig: "{{ lookup('file', '/tmp/composer-installer.sig') }}"
  tags: composer

- name: Download Composer installer.
  # https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    force: true
    checksum: "sha384:{{ composer_installer_sig }}"
  tags: composer

- name: Run Composer installer.
  command: >
    {{ php_executable }} composer-installer.php {% if composer_version|default('') != '' %} --version={{ composer_version }}{% endif %}
    chdir=/tmp
  tags: composer

- name: Remove any existing composer
  file: path="{{ composer_path }}" state=absent
  tags: composer

- name: Move composer into final location
  shell: >
    mv /tmp/composer.phar {{ composer_path }}
    creates={{ composer_path }}
  tags: composer
