---
- name: Install global
  npm: name=gulp global=yes state=present
  tags: gulp

- name: Install gulp extension
  npm:
    global=yes
    state=present
    name="{{ item.name }}"
    version="{{ item.version }}"
  with_items:
    - { name: 'gulp-concat', version: '^2.6.0' }
    - { name: 'gulp-header', version: '^1.7.1' }
    - { name: 'gulp-if', version: '^1.2.5' }
    - { name: 'gulp-jshint', version: '^1.11.2' }
    - { name: 'gulp-jsonlint', version: '^1.1.0' }
    - { name: 'gulp-ng-annotate', version: '^1.1.0' }
    - { name: 'gulp-notify', version: '^2.2.0' }
    - { name: 'gulp-rename', version: '^1.2.2' }
    - { name: 'gulp-sass', version: '^2.0.4' }
    - { name: 'gulp-sourcemaps', version: '^1.5.2' }
    - { name: 'gulp-uglify', version: '^1.4.0' }
    - { name: 'gulp-util', version: '^3.0.6' }
    - { name: 'jshint-stylish', version: '^2.0.1' }
    - { name: 'yargs', version: '^3.23.0' }
    - { name: 'browser-sync', version: '^2.10.0' }
    - { name: 'gulp-help', version: '^1.6.1' }
    - { name: 'gulp-stylelint', version: '^2.0.2' }
    - { name: 'gulp-postcss', version: '^6.1.1' }
    - { name: 'autoprefixer', version: '^6.3.7' }
    - { name: 'globby', version: '^5.0.0' }
    - { name: 'eslint', version: '^3.0.0' }
    - { name: 'chalk', version: '^1.1.3' }
  tags: gulp
